sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
    directories:
    - $HOME/.m2

script:
- mvn clean package
- mvn test
- docker build -t jm5619/ir-user .

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push jm5619/ir-user
