kumuluzee:
  name: user-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
#    checks:
#      data-source-health-check:
#        jndi-name: jdbc/UsersDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: orders-endpoint
        url-pattern: /v1/users/*


rest-config:
  endpoint-enabled: true
  healthy: true
  load-intensity: 45
