kumuluzee:
  name: user-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/IRuserDS
      connection-url: jdbc:postgresql://localhost:5432/igloo
      username: dbusers
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-check:
        jndi-name: jdbc/IRuserDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: orders-endpoint
        url-pattern: /v1/users/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="orders">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="0c188cf4-007d-4939-9026-94d12be1f725-ls.logit.io" port="16942" protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="info"/>
                          </Root>
                      </Loggers>
                  </Configuration>'


rest-config:
  endpoint-enabled: true
  healthy: true
  load-intensity: 45
